title: "Deep Reinforcement Learning for Competitive Agents in Real-Time Strategy Games: Application to the MicroRTS Environment"
description: "Supplementary Materials for Work-In-Progress Paper"
author: "Mathis Delsart"
theme: jekyll-theme-cayman
